import {
  addressFormats,
  allLanguages,
  cities,
  continents,
  countries,
  countryGeography,
  currencies,
  flagData,
  galaxies,
  getSupportedLanguages,
  languageVariants,
  languages,
  moonPhases,
  moons,
  phoneCountryCodes,
  planets,
  states,
  stars,
  timezones,
  worldMapCountries,
} from "../../../../packages/data/src/index.js";
import { ok } from "../response.js";

export function handleMetaRoute(): Response {
  return ok(
    {
      name: "arev",
      supportedLanguages: getSupportedLanguages(),
      resources: {
        countries: countries.length,
        addressFormats: addressFormats.length,
        phoneCodes: phoneCountryCodes.length,
        timezones: timezones.length,
        cities: cities.length,
        states: states.length,
        moonPhases: moonPhases.length,
        planets: planets.length,
        moons: moons.length,
        stars: stars.length,
        galaxies: galaxies.length,
        continents: continents.length,
        currencies: currencies.length,
        geography: countryGeography.length,
        flags: flagData.length,
        languages: languages.length,
        languageVariants: languageVariants.length,
        allLanguages: allLanguages.length,
        worldMapCountries: worldMapCountries.length,
      },
      routes: [
        "/health",
        "/meta",
        "/access/signup",
        "/access/verify",
        "/access/request-upgrade",
        "/address-formats",
        "/address-formats/:alpha2",
        "/countries",
        "/countries/:alpha2",
        "/cities",
        "/cities/capital/:alpha2",
        "/astronomy",
        "/phone-codes",
        "/timezones",
        "/maps/world",
      ],
    },
    undefined,
    {
      headers: {
        "cache-control": "public, max-age=3600, s-maxage=86400",
      },
    }
  );
}
